<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\User;
use App\Models\Level;
use App\Models\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class ClassroomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        $now = Carbon::now();
        $oneMonthAgo  = $now->copy()->subMonth();
        
        // Define classroom data
        $classrooms = [
            [
                'course_id' => 1, 
                'batch_id' => 1, 
                'user_id' => 1, 
                'duration' => '2 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 2, 
                'batch_id' => 1, 
                'user_id' => 1, 
                'duration' => '2 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 4, 
                'batch_id' => 1, 
                'user_id' => 2, 
                'duration' => '2 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 5, 
                'batch_id' => 1, 
                'user_id' => 2, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 7, 
                'batch_id' => 1, 
                'user_id' => 3, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 8, 
                'batch_id' => 1, 
                'user_id' => 3, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 10, 
                'batch_id' => 1, 
                'user_id' => 4, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 11, 
                'batch_id' => 1, 
                'user_id' => 4, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 13, 
                'batch_id' => 1, 
                'user_id' => 5, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 14, 
                'batch_id' => 1, 
                'user_id' => 5, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 16, 
                'batch_id' => 1, 
                'user_id' => 6, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
            [
                'course_id' => 17, 
                'batch_id' => 1, 
                'user_id' => 6, 
                'duration' => '3 months', 
                'start_date' => '2023-01-01', 
                'days' => 'Mon, Wed, Fri',
                'from' => '09:00 AM', 
                'to' => '11:00 AM', 
                'avaliable_students' => 20, 
                'accept_students' => 0, 
                'fee' => '100000', 
                'class_type' => 0, 
                'online_info_id' => null, 
                'status' => 1, 
                'created_at' => $oneMonthAgo ->copy()->addDays(14),
                'updated_at' => $oneMonthAgo ->copy()->addDays(14),
            ],
        ];

        // Insert the classroom data into the table
        DB::table('classrooms')->insert($classrooms);
    }

}
